<?php
    $config = array(
        array( // standard printer
            array(# standard label [1]
                'numx'  =>  2,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 25,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  18,
                'ybarcodetext'  =>  29,
                'whtml' =>  86.5,
                'yhtml' =>  35,
            ),
            array(# standard label long [2]
                'numx'  =>  2,
                'numy'  =>  1,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  18,
                'ybarcodetext'  =>  29,
                'whtml' =>  86.5,
                'yhtml' =>  35
            ),
            array(# crowded sheet label [3]
                'numx'  =>  2,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  18,
                'ybarcodetext'  =>  29,
                'whtml' =>  86.5,
                'yhtml' =>  35,
            ),
            array(# bryophyte label, 3 per page [4]
                'numx'  =>  1,
                'numy'  =>  3,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 15,
                'wheader'   =>  160,
                'xbarcode'  =>  152.5,
                'ybarcode'  =>  6,
                'ybarcodetext'  =>  17,
                'whtml' =>  195,
                'yhtml' =>  25
            ),
            array(# bryophyte label, 2 per page [5]
                'numx'  =>  1,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader'   =>  160,
                'xbarcode'  =>  152.5,
                'ybarcode'  =>  6,
                'ybarcodetext'  =>  17,
                'whtml' =>  195,
                'yhtml' =>  25
            ),
            array(# duplicate label [6]
                'numx'  =>  2,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  125,
                'ybarcodetext'  =>  136,
                'whtml' =>  86.5,
                'yhtml' =>  20
            ),
            array(# duplicate label long [7]
                'numx'  =>  2,
                'numy'  =>  1,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  120,
                'ybarcodetext'  =>  131,
                'whtml' =>  86.5,
                'yhtml' =>  20
            ),
            array(# spirit jar label [8]
                'numx'  =>  3,
                'numy'  =>  10,
                'labelheight' => 25.5,
                'labelwidth' => 68.2,
                'wheader' => 57,
                'yheader' => 26,
                'whtml' =>  57,
                'yhtml' =>  30,
                'xpos'  =>  7,
            ),
            array(# multisheet label [9]
                'numx'  =>  3,
                'numy'  =>  10,
                'labelheight' => 25.5,
                'labelwidth' => 68.2,
                'wheader' => 57,
                'yheader' => 26,
                'whtml' =>  57,
                'yhtml' =>  30,
                'xpos'  =>  7,
            ),
            array(# type folder label [10]
                'numx'  =>  1,
                'numy'  =>  12,
                'wheader' => FALSE,
                'yheader' => FALSE,
                'barcode' => true,
                'whtml' =>  195.5,
                'yhtml' =>  3,
                'xpos'  =>  7.5
            ),
            array(# barcode label[11]
                'numx'  =>  3,
                'numy'  =>  10,
                'wheader' => FALSE,
                'yheader' => FALSE,
                'barcode' => true,
                'labelheight' => 25.5,
                'labelwidth' => 69.2,
                'xbarcode'  =>  8,
                'ybarcode'  =>  26,
                'ybarcodetext'  =>  37,
                'whtml' =>  68,
                'yhtml' =>  26,
                'xpos'  =>  4,
            ),
 /*           array(# carpol. card [17]
                'numx'  =>  1,
                'numy'  =>  1,
                'orientation' => 'L',
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 12,
                'wheader' => 127,
                'xbarcode'  =>  233.5,
                'ybarcode'  =>  7,
                'ybarcodetext'  =>  18,
                'whtml' =>  178,
                'yhtml' =>  22,
                'yheader' => 7.5,
                'xpos' => 99,
                'height' => 127,
                'width' => 203,
            )
 */
            array(# spirit card [12]
                'numx'  =>  1,
                'numy'  =>  1,
                'orientation' => 'L',
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 12,
                'wheader' => 87,
                'xbarcode'  =>  236.5,
                'ybarcode'  =>  13,
                'ybarcodetext'  =>  24,
                'whtml' =>  129.5,
                'yhtml' =>  22,
                'yheader' => 7.5,
                'xpos' => 152.5,
                'spiritinfo' => true,
                'width' => 150,
                'height' => 103,
            ),
            array(# seedbank duplicate label [13]
                'numx'  =>  2,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  120,
                'ybarcodetext'  =>  131,
                'whtml' =>  86.5,
                'yhtml' =>  35
            ),
            array(# seedbank duplicate label long [14]
                'numx'  =>  2,
                'numy'  =>  1,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  120,
                'ybarcodetext'  =>  131,
                'whtml' =>  86.5,
                'yhtml' =>  35
            ),
            array(# annotation label [15]
                'numx'  =>  3,
                'numy'  =>  10,
                'labelheight' => 25.5,
                'labelwidth' => 68.2,
                'wheader' => 57,
                'yheader' => 24,
                'whtml' =>  57,
                'yhtml' =>  28,
                'xpos'  =>  7,
            ),
            array(# annotation label with det. notes [16]
                'numx'  =>  3,
                'numy'  =>  10,
                'labelheight' => 26.3,
                'labelwidth' => 71.1,
                'wheader' => 60,
                'yheader' => 20,
                'whtml' =>  60,
                'yhtml' =>  24,
                'xpos'  =>  4,
            ),
            array(# carpol. card [17]
                'numx'  =>  1,
                'numy'  =>  1,
                'orientation' => 'L',
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 12,
                'wheader' => 127,
                'xbarcode'  =>  233.5,
                'ybarcode'  =>  7,
                'ybarcodetext'  =>  18,
                'whtml' =>  178,
                'yhtml' =>  22,
                'yheader' => 7.5,
                'xpos' => 99,
                'height' => 127,
                'width' => 203,
            ),
            array(# silica gel sample label [18]
                'numx'  =>  3,
                'numy'  =>  10,
                'labelheight' => 25.5,
                'labelwidth' => 68.2,
                'wheader' => 57,
                'yheader' => 26,
                'whtml' =>  57,
                'yhtml' =>  30,
                'xpos'  =>  7,
            ),
            array(# VRS label [19]
                'numx'  =>  2,
                'numy'  =>  2,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  true,
                'footeroffsety' => 25,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  20,
                'ybarcodetext'  =>  31,
                'whtml' =>  86.5,
                'yhtml' =>  35,
            ),
            array(# VRS barcode label[20]
                'numx'  =>  3,
                'numy'  =>  10,
                'wheader' => FALSE,
                'yheader' => FALSE,
                'barcode' => true,
                'labelheight' => 25.5,
                'labelwidth' => 69.2,
                'xbarcode'  =>  8,
                'ybarcode'  =>  26,
                'ybarcodetext'  =>  37,
                'whtml' =>  68,
                'yhtml' =>  26,
                'xpos'  =>  4,
            ),
            array(# VRS label long [21]
                'numx'  =>  2,
                'numy'  =>  1,
                'barcode'   =>  true,
                'footerpositionabsolute'    =>  false,
                'wheader' => 87,
                'xbarcode'  =>  44.5,
                'ybarcode'  =>  20,
                'ybarcodetext'  =>  31,
                'whtml' =>  86.5,
                'yhtml' =>  35
            ),
            
        ),    );
?>
